name: Test Plan
on:
  push:
    branches: [ main ]
    paths: [ "test/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "test/**" ]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
          terraform_wrapper: false
      
      - name: Terraform Plan
        env:
          TF_VAR_alicloud_access_key: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          TF_VAR_alicloud_secret_key: ${{ secrets.ALICLOUD_SECRET_KEY }}
        run: |
          cd test
          terraform init -backend-config="bucket=tf-state-bucket" -backend-config="key=test/terraform.tfstate"
          terraform plan -out=tfplan
